ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # 1. Sensör: Tekerlek Odometrisi
    odom0: wheel/odom
    odom0_config: [false, false, false, # X, Y, Z (Pozisyon)
                   false, false, false, # Roll, Pitch, Yaw
                   true,  false, false, # X Hızı (Düz gidişe güven)
                   false, false, false, # Roll, Pitch Hızları
                   false, false, false] # Yaw Hızı (Dönüşe GÜVENME!)

    # 2. Sensör: Lidar Odometrisi
    odom1: laser/odom
    odom1_config: [false, false, false, 
                   false, false, false, 
                   false, true,  false, # Y Hızı (Lidar'dan al)
                   false, false, false, 
                   false, false, true]  # Yaw Hızı (Dönüşlerde Lidar'a GÜVEN!)